# Generated by Django 3.0.6 on 2020-05-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbug', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='display_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
